
name: develop_branch
on:
  push:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f environment.yml ]; then pip install -r environment.yml; fi
    - name: Test with pytest
      run: |
        pytest tests/unit_tests