name: develop_pullrequests
on:
  pull_request:
    branches: 
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint
      run: |
        python lint.py --path ./feature_extraction --threshold 9
        python lint.py --path ./models --threshold 9
        python lint.py --path ./tests --threshold 9
        python lint.py --path ./utils --threshold 9
    - name: Test with pytest
      run: |
        pytest tests/unit_tests